name: Build & Test Debug

on:
  push:
    branches: [ master ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master ]

jobs:
  build:
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3.6.0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Debug --no-restore /p:WarningsAsErrors=nullable /m

      - name: Run Tests
        run: dotnet test --no-build --configuration Debug
